server:
  port: ${port:8080}
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
  application:
    name: user-service
mybatis:
  type-aliases-package: com.example.pojo
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1000/eureka
  #使用ip地址注册服务
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true

  #配置服务的续约
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30
testBus:
  name: test1

